spring:
  #  datasource:
  #    url: jdbc:mysql://
  #    username:
  #    password:
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:mem:testdb
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: FIXME
            client-secret: FIXME
          facebook:
            client-id: FIXME
            client-secret: FIXME
logging:
  level:
    root: DEBUG
server:
  port: 5000 # AWS Nginx default port

custom:
  oauth2:
    kakao:
      client-id: FIXME
      client-secret: FIXME
